# foundry.toml

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache_forge"
solc_version = "0.8.24" # Good to pin this
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
# For Arbitrum Sepolia
arbitrum_sepolia = "${ARB_SEPOLIA_RPC_URL}" # Ensure ARB_SEPOLIA_RPC_URL is defined in your .env

# You can add other networks here, e.g.:
# localhost = "http://127.0.0.1:8545"
# mainnet = "${MAINNET_RPC_URL}"

[etherscan]
# Configuration for Arbitrum Sepolia on Arbiscan
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", chain = 421614, url = "https://api-sepolia.arbiscan.io/api" }
# Ensure ARBISCAN_API_KEY is defined in your .env
# The chain ID 421614 for Arbitrum Sepolia is correct.
# The API URL https://api-sepolia.arbiscan.io/api for Arbitrum Sepolia is correct.

# You can add configurations for other Etherscan-compatible explorers:
# goerli = { key = "${ETHERSCAN_API_KEY}", chain = "goerli" }
# mainnet = { key = "${ETHERSCAN_API_KEY}", chain = "mainnet" }